### ISSUE TITLE
IT Management as Domain in Sidebar

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/it_management#212]
https://docs.erpnext.com/docs/user/manual/en/setting-up/domain-settings

![grafik](https://user-images.githubusercontent.com/22279621/117482410-a08b3480-af64-11eb-9565-c30d9037c038.png)

**Comment by wojosc** [comment]
@kkulloters

In ERPNext we have so called domains. These are a collection of Doctypes which are active when ticking the box. This function could be implemented at some point also. Please read https://docs.erpnext.com/docs/user/manual/en/setting-up/domain-settings for a quick overview.

Domains are shown in the new (v13) sidebar in the section "DOMAINS". In the picture in the post above you can see "Fertigung" (which is manufacturing).

Out IT Management Custom App is now (since v13) hidden, as the card, that used to be shown in v12 is now gone and not part of the new desk/app function in v13.

We would like to see our IT Management Domain in that sidebar...

**Comment by wojosc** [comment]
@canlann is this what we might need also? a "workspace file" https://github.com/frappe/nextcloud-integration/pull/22

**Comment by canlann** [comment]
@wojosc mhmm looks like what we need

**Comment by canlann** [comment]
Solved by creating a Workspace ( doctype Workspace ) and switching the is_standard flag in the database to 1

**Comment by canlann** [comment]
![grafik](https://user-images.githubusercontent.com/11473213/128702972-e86f5359-e168-4169-8235-97ee1375f70b.png)

**Comment by canlann** [comment]
The octicon icons available can be viewed in this file: /home/frappe/frappe-bench/apps/frappe/frappe/public/icons/timeless/symbol-defs.svg

**Comment by wojosc** [comment]
Nice nice.

What will it take to get it under the Domains section?

**Comment by canlann** [comment]
I believe it is a Module. The exact definition difference between module and domain is not known to me. I would have to learn this

**Comment by wojosc** [comment]
https://phamos.eu/blog/customizing/eine-eigene-erpnext-domain-sichtbar-machen
