### ISSUE TITLE
Get Items from IT Checklist reverses position order in task

### ISSUE THREAD

**Issue by canlann** [phamos-eu/it_management#220]
This is the positions in the IT Checklist

![image](https://user-images.githubusercontent.com/11473213/134674230-9b2e02b0-49a8-4b7a-9b03-86aee338664b.png)

This is the positions when loaded in the Task via Get Items-Button

![image](https://user-images.githubusercontent.com/11473213/134674371-ff41cbbf-7521-4fbb-9cdf-fbc42b8a1545.png)

**Comment by wojosc** [comment]
this is not an issue on latest version installed via frappecloud
![get_items_from_it_checklist](https://user-images.githubusercontent.com/22279621/162588817-920b179a-a3bb-4483-aae6-668b1ee59019.gif)
