### ISSUE TITLE
Mandatory fields required in Solution - Customer

### ISSUE THREAD

**Issue by hreisenb** [phamos-eu/it_management#234]
Beim Anlegen einer Solution wird die Eingabe vom Kunden überschrieben und folgende Meldung angezeigt:
![image](https://user-images.githubusercontent.com/44806714/172993518-96bff064-48ff-4265-937a-e3cf3452bdae.png)

Aus einer IT Landscape heraus eine Solution anzulegen funktioniert.

**Comment by wojosc** [comment]
Fixed with https://github.com/phamos-eu/it_management/commit/c88a942bfaf1e02bc8d9d65e96e756b7c2b92716

![grafik](https://user-images.githubusercontent.com/22279621/173087356-8424cfe4-c010-4013-822e-13405b9eacb8.png)
