### ISSUE TITLE
Configuration Item --> Add Task ... Field not permitted in query: it_landscape

### ISSUE THREAD

**Issue by hreisenb** [phamos-eu/it_management#237]
![image](https://user-images.githubusercontent.com/44806714/173286991-db89b0db-956d-428a-b1b4-59988d9eda15.png)

**Comment by wojosc** [comment]
fixed with: https://github.com/phamos-eu/it_management/commit/0b6f4c88ba99b249a8c46eeafc7c08ee885bbafa
