### ISSUE TITLE
it management does not appear on frappe

### ISSUE THREAD

**Issue by darkfritz2** [phamos-eu/it_management#248]
hello,

i have installed the application on a self hosted VPS but after installation it management does not appear on frappe app page. 
i'm new to this so i don't know if i have to refresh, reload something or i have to create the workspace from scratch.

**Comment by wojosc** [comment]
Hi!

unfortunatelly we do not have a preset workspace for this yet. You will find the doctypes when going to your doctype list and then setting the filter in Modul for IT Management.

Also you can build your own workspace (use google translate ;) ) https://doku.phamos.eu/books/erpnext-benutzerhandbuch/page/workspace

**Comment by majubewi** [comment]
hello,

no it is a little bit more complicated. i can already say that the correct way of reinstalling the "Workspace" for an application is to install the application on a development server in the newest version of frappé and build the workspace from scratch with the "Build" module and "Create Workspace".

**Comment by darkfritz2** [comment]
alles klar, danke! :)

ok. thank you.
