### ISSUE TITLE
Define Naming Prefix

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/it_management#251]
All DocTypes used in this application shall hold the prefix "ITM" to be easily distiguishable when using the app to make navigation easier and clear that the doctypes are not part of frappe or ERPNext

- [x] Decide on ITM as prefix

**Comment by wojosc** [comment]
@roquegv thinking about it I think the prefix is good and suitable. In some cases it will not be bloat e.g. IT Backup -> ITM Backup or IT Landscape -> ITM Landscape and on others it will not matter to much Software Instance -> ITM Software Instance.

What might be worth a though is if we should rather choose a Suffix instead of a Prefix. What do you think?

**Comment by roquegv** [comment]
Yes, I prefer to use prefix as in that way the doctype names are more clear and searchable.

**Comment by roquegv** [comment]
These should be the new names for the doctypes:

| Old Name                           | New Name                               |
|------------------------------------|----------------------------------------|
| IT Checklist                       | ITM Checklist                          |
| Licence                            | ITM Licence                            |
| IT Backup                          | ITM Backup                             |
| User Account                       | ITM User Account                       |
| Solution                           | ITM Solution                           |
| User Group                         | ITM User Group                         |
| Subnet                             | ITM Subnet                             |
| IT Landscape                       | ITM Landscape                          |
| Configuration Item                 | ITM Configuration Item                 |
| User Account Type                  | ITM User Account Type                  |
| Location Room                      | ITM Location Room                      |
| Socket                             | ITM Socket                             |
| IT Management Table                | ITM Management Table                   |
| Network Interface Controller       | ITM Network Interface Controller       |
| Software Instance                  | ITM Software Instance                  |
| Solution Table                     | ITM Solution Table                     |
| Host Domain                        | ITM Host Domain                        |
| Location                           | ITM Location                           |
| Task Multiselect                   | ITM Task Multiselect                   |
| IT Management Settings             | ITM Management Settings                |
| IT Hardware                        | ITM Hardware                           |
| Trip                               | ITM Trip                               |
| Retention Type                     | ITM Retention Type                     |
| Contact Multiselect                | ITM Contact Multiselect                |
| Solution Multiselect               | ITM Solution Multiselect               |
| Configuration Item Multiselect     | ITM Configuration Item Multiselect     |
| IT Software                        | ITM Software                           |
| Network Interface Controller Table | ITM Network Interface Controller Table |
| Local Area Network                 | ITM Local Area Network                 |
| Floor                              | ITM Floor                              |
| Subnet Table                       | ITM Subnet Table                       |
| IT Checklist Type                  | ITM Checklist Type                     |
| IT Service Report                  | ITM Service Report                     |
| User Group Table                   | ITM User Group Table                   |
| IT Checklist Table                 | ITM Checklist Table                    |
| Contact Table                      | ITM Contact Table                      |
| IP Address                         | ITM IP Address                         |
| User Group Type                    | ITM User Group Type                    |
| Cycle Type                         | ITM Cycle Type                         |
| Encryption Type                    | ITM Encryption Type                    |
| Configuration Item Type            | ITM Configuration Item Type            |
| Licence Table                      | ITM Licence Table                      |
| User Account Table                 | ITM User Account Table                 |
| Solution Type                      | ITM Solution Type                      |
| Software Instance Table            | ITM Software Instance Table            |
| Network Jack                       | ITM Network Jack                       |
| Configuration Item Table           | ITM Configuration Item Table           |
| Task Checklist                     | ITM Task Checklist                     |
| Task Configuration Item Table      | ITM Task Configuration Item Table      |
| Location Room Table                | ITM Location Room Table                |
| Project Configuration Item Table   | ITM Project Configuration Item Table   |
| Storage                            | ITM Storage                            |
| Software Version                   | ITM Software Version                   |

**Comment by wojosc** [comment]
@lajidey look, we have already had done some work on this is the past.

At the moment we are not following this guide-line with "ITM IT Landscape" Doctype. Let's just keep that as an exception for now and make sure that we follow suite in the future.
